# Generated by Django 5.1 on 2024-10-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_paid_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
    ]
